# Generated by Django 5.1.6 on 2025-03-23 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_jwttoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JWTToken',
        ),
    ]
