# Generated by Django 5.1.6 on 2025-03-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='access',
            field=models.TextField(default='Default access text'),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='refresh_token',
            field=models.TextField(default='Default refresh text'),
        ),
    ]
